import type { User } from "@/app/types";

// Mock users data for the dashboard
export const mockUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    role: "admin",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    createdAt: "2024-01-15T10:30:00Z",
    lastLogin: "2024-01-14T09:15:00Z",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@company.com",
    role: "editor",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    createdAt: "2024-02-20T14:45:00Z",
    lastLogin: "2024-01-13T16:30:00Z",
  },
  {
    id: "3",
    name: "Emily Davis",
    email: "emily.davis@company.com",
    role: "user",
    status: "pending",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    createdAt: "2024-03-10T08:00:00Z",
    lastLogin: null,
  },
  {
    id: "4",
    name: "James Wilson",
    email: "james.wilson@company.com",
    role: "user",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    createdAt: "2024-01-05T11:20:00Z",
    lastLogin: "2024-01-14T08:45:00Z",
  },
  {
    id: "5",
    name: "Amanda Martinez",
    email: "amanda.martinez@company.com",
    role: "editor",
    status: "inactive",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
    createdAt: "2023-11-28T15:10:00Z",
    lastLogin: "2023-12-20T10:00:00Z",
  },
  {
    id: "6",
    name: "Christopher Brown",
    email: "chris.brown@company.com",
    role: "user",
    status: "pending",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris",
    createdAt: "2024-01-12T09:30:00Z",
    lastLogin: null,
  },
  {
    id: "7",
    name: "Jessica Taylor",
    email: "jessica.taylor@company.com",
    role: "admin",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jessica",
    createdAt: "2023-08-15T13:45:00Z",
    lastLogin: "2024-01-14T11:00:00Z",
  },
  {
    id: "8",
    name: "Daniel White",
    email: "daniel.white@company.com",
    role: "editor",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel",
    createdAt: "2023-10-20T16:20:00Z",
    lastLogin: "2024-01-13T14:30:00Z",
  },
  {
    id: "9",
    name: "Olivia Anderson",
    email: "olivia.anderson@company.com",
    role: "user",
    status: "inactive",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia",
    createdAt: "2023-12-01T10:00:00Z",
    lastLogin: "2024-01-01T09:00:00Z",
  },
  {
    id: "10",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "user",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    createdAt: "2024-01-08T08:15:00Z",
    lastLogin: "2024-01-14T10:45:00Z",
  },
  {
    id: "11",
    name: "Sophie Clark",
    email: "sophie.clark@company.com",
    role: "editor",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    createdAt: "2023-09-25T12:30:00Z",
    lastLogin: "2024-01-12T15:20:00Z",
  },
  {
    id: "12",
    name: "Ryan Thompson",
    email: "ryan.thompson@company.com",
    role: "user",
    status: "pending",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan",
    createdAt: "2024-01-13T14:00:00Z",
    lastLogin: null,
  },
  {
    id: "13",
    name: "Emma Rodriguez",
    email: "emma.rodriguez@company.com",
    role: "user",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    createdAt: "2023-11-10T09:45:00Z",
    lastLogin: "2024-01-14T07:30:00Z",
  },
  {
    id: "14",
    name: "Lucas Garcia",
    email: "lucas.garcia@company.com",
    role: "admin",
    status: "active",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas",
    createdAt: "2023-07-20T11:00:00Z",
    lastLogin: "2024-01-14T12:00:00Z",
  },
  {
    id: "15",
    name: "Mia Lee",
    email: "mia.lee@company.com",
    role: "editor",
    status: "inactive",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mia",
    createdAt: "2023-10-05T15:30:00Z",
    lastLogin: "2023-12-15T10:15:00Z",
  },
];

// Simulate network delay for mock API
export const simulateDelay = (ms: number) =>
  new Promise((r) => setTimeout(r, ms));
